kind: pipeline
name: GNU GCC TC ARM BUILD

steps:
- name: GNU GCC ARM
  image: archlinux:latest
  environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
  commands:
    - "export GITHUB_TOKEN"
    - pacman -Sy base-devel git subversion autoconf-archive tar xz pixz lzip aria2 zip parallel zstd rsync python python3 --noconfirm
    - git clone https://github.com/theradcolor/build-tools-gcc.git
    - bash build -a arm -s gnu -v 10 -V -p zstd -tr

---
kind: pipeline
name: GNU GCC TC ARM64 BUILD

steps:
- name: GNU GCC ARM64
  image: archlinux:latest
  environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
  commands:
    - "export GITHUB_TOKEN"
    - pacman -Sy base-devel git subversion autoconf-archive tar xz pixz lzip aria2 zip parallel zstd rsync python python3 --noconfirm
    - git clone https://github.com/theradcolor/build-tools-gcc.git
    - bash build -a arm64 -s gnu -v 10 -V -p zstd -tr
    
trigger:
  branch:
    - stable-gcc
